### PR TITLE
Fixed Deprecated API calls

### PR DESCRIPTION
**Pull request by loklaan**
Silence to deprecation cop.

### CODE REVIEW

**Comment by alexchee** [comment]
:+1: now atom disables this package becuase of the deprecations

**Comment by smeggingsmegger** [comment]
:: bump ::

**Comment by deiga** [comment]
Please merge and publish!

**Comment by robhurring** [comment]
Sorry for the delay - was stuck in a hospital for the past few days. Publishing now

**Comment by loklaan** [comment]
No worries! Hope everything is OK :mask:

**Comment by robhurring** [comment]
We had a baby :D Everything is great, but still pretty hectic haha. Thanks again for helping out with this!

**Comment by alexchee** [comment]
Congrats! :tada:

**Pull request merged**
