### PR TITLE
Change case of all words in selection OR at each cursor.

### PR DESCRIPTION
**Pull request by khyo**
I know previously the module changed from operating on selection to operating on cursors. That's great most of the time. But when the user needs to convert an entire page, list, array, or collection of words this pull request should make it seem-less.

### CODE REVIEW

**Comment by khyo** [comment]
I'll fix the tests.

**Comment by deiga** [comment]
Does #23 make this one obsolete? @khyo

**Comment by deiga** [comment]
@khyo Hey, any update on the failing test? This is a much needed update.

**Comment by deiga** [comment]
This is resolved by #23 
Thank you for your contribution!

**Pull request closed without merging**
